# Required
version: 2

# Image to use
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

# Configuration
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
